# Generated by Django 3.2 on 2022-02-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_review_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
