# Generated by Django 3.2 on 2022-02-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_makereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_title', models.CharField(max_length=200)),
                ('user_location', models.CharField(max_length=100)),
                ('user_reviewbody', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='review.review')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
