# Generated by Django 3.2 on 2022-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_delete_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
